version: "3.8"

services:

  api:
    build: ./API
    container_name: api_service
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: always  

  front:
    build: ./Front
    container_name: front_service
    ports:
      - "5009:5009"
    env_file:
      - .env
    restart: always    