version: "3.8"

services:

  account_service:
    build: ./Account_Service
    container_name: account_service
    ports:
      - "5002:5002"
    env_file:
      - .env
    restart: always

  case_service:
    build: ./Case_Service
    container_name: case_service
    ports:
      - "5003:5003"
    env_file:
      - .env
    restart: always

  entity_service:
    build: ./Entity_Service
    container_name: entity_service
    ports:
      - "5004:5004"
    env_file:
      - .env
    restart: always

  forms_service:
    build: ./Forms_Service
    container_name: forms_service
    ports:
      - "5005:5005"
    env_file:
      - .env
    restart: always

  user_service:
    build: ./User_Service
    container_name: user_service
    ports:
      - "5006:5006"
    env_file:
      - .env
    restart: always

  notification_service:
    build: ./Notification_Service
    container_name: notification_service
    ports:
      - "5007:5007"
    env_file:
      - .env
    restart: always

  auth_service:
    build: ./Authenticator_Service
    container_name: auth_service
    ports:
      - "5008:5008"
    env_file:
      - .env
    restart: always

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: always