INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user1', 'hash1', 'user', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user2', 'hash2', 'admin', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user3', 'hash3', 'user', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user4', 'hash4', 'admin', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user5', 'hash5', 'user', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user6', 'hash6', 'admin', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user7', 'hash7', 'user', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user8', 'hash8', 'admin', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user9', 'hash9', 'admin', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user10', 'hash10', 'admin', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user11', 'hash11', 'admin', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user12', 'hash12', 'user', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user13', 'hash13', 'admin', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user14', 'hash14', 'admin', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user15', 'hash15', 'user', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user16', 'hash16', 'admin', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user17', 'hash17', 'admin', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user18', 'hash18', 'admin', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user19', 'hash19', 'admin', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user20', 'hash20', 'user', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user21', 'hash21', 'admin', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user22', 'hash22', 'user', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user23', 'hash23', 'admin', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user24', 'hash24', 'admin', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user25', 'hash25', 'admin', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user26', 'hash26', 'user', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user27', 'hash27', 'admin', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user28', 'hash28', 'user', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user29', 'hash29', 'admin', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user30', 'hash30', 'user', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user31', 'hash31', 'user', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user32', 'hash32', 'user', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user33', 'hash33', 'user', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user34', 'hash34', 'admin', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user35', 'hash35', 'admin', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user36', 'hash36', 'user', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user37', 'hash37', 'admin', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user38', 'hash38', 'user', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user39', 'hash39', 'user', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user40', 'hash40', 'user', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user41', 'hash41', 'admin', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user42', 'hash42', 'user', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user43', 'hash43', 'admin', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user44', 'hash44', 'admin', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user45', 'hash45', 'admin', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user46', 'hash46', 'user', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user47', 'hash47', 'user', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user48', 'hash48', 'user', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user49', 'hash49', 'admin', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user50', 'hash50', 'admin', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user51', 'hash51', 'admin', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user52', 'hash52', 'user', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user53', 'hash53', 'user', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user54', 'hash54', 'admin', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user55', 'hash55', 'admin', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user56', 'hash56', 'user', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user57', 'hash57', 'user', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user58', 'hash58', 'user', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user59', 'hash59', 'user', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user60', 'hash60', 'admin', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user61', 'hash61', 'admin', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user62', 'hash62', 'user', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user63', 'hash63', 'user', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user64', 'hash64', 'admin', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user65', 'hash65', 'admin', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user66', 'hash66', 'user', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user67', 'hash67', 'user', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user68', 'hash68', 'admin', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user69', 'hash69', 'user', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user70', 'hash70', 'user', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user71', 'hash71', 'admin', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user72', 'hash72', 'user', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user73', 'hash73', 'user', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user74', 'hash74', 'user', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user75', 'hash75', 'admin', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user76', 'hash76', 'admin', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user77', 'hash77', 'user', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user78', 'hash78', 'admin', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user79', 'hash79', 'user', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user80', 'hash80', 'user', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user81', 'hash81', 'admin', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user82', 'hash82', 'admin', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user83', 'hash83', 'admin', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user84', 'hash84', 'user', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user85', 'hash85', 'admin', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user86', 'hash86', 'user', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user87', 'hash87', 'user', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user88', 'hash88', 'admin', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user89', 'hash89', 'user', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user90', 'hash90', 'admin', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user91', 'hash91', 'user', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user92', 'hash92', 'user', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user93', 'hash93', 'user', 'inactive');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user94', 'hash94', 'admin', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user95', 'hash95', 'admin', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user96', 'hash96', 'admin', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user97', 'hash97', 'admin', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user98', 'hash98', 'user', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user99', 'hash99', 'user', 'active');
INSERT INTO tbl_user (Username, Password_Hash, Fk_Role, Fk_State) VALUES ('user100', 'hash100', 'user', 'inactive');
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 1', '1001-XYZ', 1996, 775, 'Francés', 1, 1);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 2', '1002-XYZ', 1991, 241, 'Inglés', 4, 2);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 3', '1003-XYZ', 1989, 157, 'Español', 3, 3);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 4', '1004-XYZ', 1975, 343, 'Español', 4, 1);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 5', '1005-XYZ', 2008, 509, 'Español', 5, 3);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 6', '1006-XYZ', 1975, 414, 'Español', 4, 3);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 7', '1007-XYZ', 2001, 703, 'Español', 1, 3);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 8', '1008-XYZ', 2001, 300, 'Español', 1, 2);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 9', '1009-XYZ', 1958, 286, 'Español', 5, 2);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 10', '1010-XYZ', 1990, 798, 'Francés', 5, 3);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 11', '1011-XYZ', 1963, 734, 'Inglés', 2, 2);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 12', '1012-XYZ', 2012, 633, 'Francés', 5, 2);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 13', '1013-XYZ', 1952, 231, 'Español', 1, 2);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 14', '1014-XYZ', 1971, 714, 'Francés', 1, 1);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 15', '1015-XYZ', 1989, 237, 'Español', 1, 2);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 16', '1016-XYZ', 1993, 452, 'Inglés', 2, 2);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 17', '1017-XYZ', 2003, 514, 'Español', 2, 1);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 18', '1018-XYZ', 1977, 771, 'Francés', 1, 2);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 19', '1019-XYZ', 2011, 436, 'Inglés', 5, 1);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 20', '1020-XYZ', 1979, 560, 'Francés', 1, 1);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 21', '1021-XYZ', 2022, 707, 'Español', 4, 3);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 22', '1022-XYZ', 2004, 119, 'Inglés', 3, 2);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 23', '1023-XYZ', 1977, 720, 'Español', 5, 3);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 24', '1024-XYZ', 1978, 496, 'Español', 3, 3);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 25', '1025-XYZ', 1997, 228, 'Español', 1, 2);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 26', '1026-XYZ', 2015, 289, 'Español', 5, 2);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 27', '1027-XYZ', 1982, 354, 'Inglés', 4, 2);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 28', '1028-XYZ', 2025, 754, 'Inglés', 1, 3);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 29', '1029-XYZ', 1973, 178, 'Inglés', 5, 1);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 30', '1030-XYZ', 1953, 404, 'Inglés', 2, 1);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 31', '1031-XYZ', 1999, 376, 'Inglés', 2, 1);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 32', '1032-XYZ', 1981, 285, 'Español', 3, 1);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 33', '1033-XYZ', 1959, 625, 'Inglés', 1, 3);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 34', '1034-XYZ', 2006, 604, 'Inglés', 1, 2);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 35', '1035-XYZ', 2023, 762, 'Inglés', 2, 3);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 36', '1036-XYZ', 1958, 380, 'Inglés', 5, 2);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 37', '1037-XYZ', 2016, 237, 'Inglés', 2, 1);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 38', '1038-XYZ', 1985, 337, 'Francés', 3, 3);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 39', '1039-XYZ', 1980, 134, 'Español', 3, 1);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 40', '1040-XYZ', 2006, 717, 'Inglés', 2, 3);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 41', '1041-XYZ', 1963, 301, 'Francés', 3, 1);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 42', '1042-XYZ', 1966, 473, 'Inglés', 3, 1);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 43', '1043-XYZ', 2019, 194, 'Inglés', 1, 3);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 44', '1044-XYZ', 1956, 627, 'Español', 2, 2);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 45', '1045-XYZ', 1969, 633, 'Español', 4, 1);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 46', '1046-XYZ', 2023, 748, 'Inglés', 5, 1);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 47', '1047-XYZ', 1978, 791, 'Español', 3, 2);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 48', '1048-XYZ', 2024, 107, 'Español', 4, 2);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 49', '1049-XYZ', 2012, 229, 'Francés', 4, 3);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 50', '1050-XYZ', 1969, 635, 'Inglés', 3, 1);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 51', '1051-XYZ', 1978, 380, 'Español', 4, 2);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 52', '1052-XYZ', 1955, 741, 'Español', 5, 3);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 53', '1053-XYZ', 1981, 458, 'Español', 5, 2);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 54', '1054-XYZ', 2012, 158, 'Inglés', 3, 1);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 55', '1055-XYZ', 1988, 741, 'Español', 4, 3);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 56', '1056-XYZ', 2021, 223, 'Francés', 4, 1);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 57', '1057-XYZ', 1970, 511, 'Español', 1, 1);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 58', '1058-XYZ', 1958, 733, 'Francés', 3, 2);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 59', '1059-XYZ', 1954, 140, 'Francés', 3, 1);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 60', '1060-XYZ', 1984, 703, 'Español', 5, 3);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 61', '1061-XYZ', 1952, 534, 'Español', 4, 3);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 62', '1062-XYZ', 1989, 406, 'Francés', 3, 3);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 63', '1063-XYZ', 1998, 371, 'Español', 3, 2);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 64', '1064-XYZ', 1973, 567, 'Francés', 4, 1);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 65', '1065-XYZ', 1984, 405, 'Español', 1, 2);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 66', '1066-XYZ', 1982, 174, 'Francés', 1, 2);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 67', '1067-XYZ', 1969, 416, 'Español', 4, 2);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 68', '1068-XYZ', 1959, 639, 'Español', 3, 1);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 69', '1069-XYZ', 1965, 264, 'Español', 1, 2);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 70', '1070-XYZ', 2004, 727, 'Inglés', 2, 3);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 71', '1071-XYZ', 1952, 554, 'Francés', 1, 1);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 72', '1072-XYZ', 1959, 333, 'Francés', 5, 3);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 73', '1073-XYZ', 1966, 654, 'Español', 4, 2);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 74', '1074-XYZ', 1965, 228, 'Español', 5, 3);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 75', '1075-XYZ', 2014, 316, 'Francés', 5, 2);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 76', '1076-XYZ', 1958, 609, 'Español', 3, 2);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 77', '1077-XYZ', 2015, 422, 'Francés', 4, 1);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 78', '1078-XYZ', 1972, 338, 'Inglés', 3, 2);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 79', '1079-XYZ', 1967, 176, 'Inglés', 3, 1);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 80', '1080-XYZ', 1988, 341, 'Español', 3, 2);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 81', '1081-XYZ', 1956, 634, 'Francés', 1, 2);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 82', '1082-XYZ', 1990, 537, 'Inglés', 5, 3);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 83', '1083-XYZ', 1961, 476, 'Inglés', 1, 2);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 84', '1084-XYZ', 1987, 266, 'Español', 4, 3);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 85', '1085-XYZ', 1969, 105, 'Inglés', 1, 1);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 86', '1086-XYZ', 1984, 479, 'Francés', 2, 3);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 87', '1087-XYZ', 2007, 331, 'Francés', 1, 2);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 88', '1088-XYZ', 1984, 561, 'Español', 3, 1);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 89', '1089-XYZ', 2011, 212, 'Inglés', 3, 3);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 90', '1090-XYZ', 1965, 755, 'Inglés', 4, 2);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 91', '1091-XYZ', 1964, 138, 'Francés', 4, 3);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 92', '1092-XYZ', 1993, 693, 'Español', 4, 2);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 93', '1093-XYZ', 2008, 656, 'Francés', 1, 1);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 94', '1094-XYZ', 1951, 319, 'Español', 3, 1);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 95', '1095-XYZ', 1985, 339, 'Inglés', 3, 3);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 96', '1096-XYZ', 1972, 317, 'Español', 4, 3);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 97', '1097-XYZ', 1995, 203, 'Inglés', 4, 2);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 98', '1098-XYZ', 1970, 567, 'Inglés', 5, 2);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 99', '1099-XYZ', 2008, 462, 'Español', 4, 1);
INSERT INTO tbl_books (Title, Isbn, Publication_Year, Pages, Language, Fk_Category, Fk_Publisher) VALUES ('Libro 100', '1100-XYZ', 2016, 232, 'Español', 2, 2);
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor1', 'Apellido1');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor2', 'Apellido2');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor3', 'Apellido3');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor4', 'Apellido4');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor5', 'Apellido5');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor6', 'Apellido6');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor7', 'Apellido7');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor8', 'Apellido8');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor9', 'Apellido9');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor10', 'Apellido10');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor11', 'Apellido11');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor12', 'Apellido12');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor13', 'Apellido13');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor14', 'Apellido14');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor15', 'Apellido15');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor16', 'Apellido16');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor17', 'Apellido17');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor18', 'Apellido18');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor19', 'Apellido19');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor20', 'Apellido20');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor21', 'Apellido21');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor22', 'Apellido22');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor23', 'Apellido23');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor24', 'Apellido24');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor25', 'Apellido25');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor26', 'Apellido26');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor27', 'Apellido27');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor28', 'Apellido28');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor29', 'Apellido29');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor30', 'Apellido30');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor31', 'Apellido31');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor32', 'Apellido32');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor33', 'Apellido33');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor34', 'Apellido34');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor35', 'Apellido35');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor36', 'Apellido36');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor37', 'Apellido37');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor38', 'Apellido38');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor39', 'Apellido39');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor40', 'Apellido40');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor41', 'Apellido41');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor42', 'Apellido42');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor43', 'Apellido43');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor44', 'Apellido44');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor45', 'Apellido45');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor46', 'Apellido46');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor47', 'Apellido47');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor48', 'Apellido48');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor49', 'Apellido49');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor50', 'Apellido50');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor51', 'Apellido51');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor52', 'Apellido52');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor53', 'Apellido53');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor54', 'Apellido54');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor55', 'Apellido55');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor56', 'Apellido56');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor57', 'Apellido57');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor58', 'Apellido58');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor59', 'Apellido59');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor60', 'Apellido60');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor61', 'Apellido61');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor62', 'Apellido62');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor63', 'Apellido63');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor64', 'Apellido64');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor65', 'Apellido65');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor66', 'Apellido66');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor67', 'Apellido67');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor68', 'Apellido68');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor69', 'Apellido69');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor70', 'Apellido70');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor71', 'Apellido71');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor72', 'Apellido72');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor73', 'Apellido73');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor74', 'Apellido74');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor75', 'Apellido75');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor76', 'Apellido76');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor77', 'Apellido77');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor78', 'Apellido78');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor79', 'Apellido79');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor80', 'Apellido80');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor81', 'Apellido81');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor82', 'Apellido82');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor83', 'Apellido83');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor84', 'Apellido84');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor85', 'Apellido85');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor86', 'Apellido86');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor87', 'Apellido87');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor88', 'Apellido88');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor89', 'Apellido89');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor90', 'Apellido90');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor91', 'Apellido91');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor92', 'Apellido92');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor93', 'Apellido93');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor94', 'Apellido94');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor95', 'Apellido95');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor96', 'Apellido96');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor97', 'Apellido97');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor98', 'Apellido98');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor99', 'Apellido99');
INSERT INTO tbl_authors (First_Name, Last_Name) VALUES ('Autor100', 'Apellido100');
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (1, 1);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (2, 2);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (3, 3);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (4, 4);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (5, 5);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (6, 6);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (7, 7);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (8, 8);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (9, 9);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (10, 10);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (11, 11);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (12, 12);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (13, 13);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (14, 14);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (15, 15);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (16, 16);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (17, 17);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (18, 18);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (19, 19);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (20, 20);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (21, 21);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (22, 22);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (23, 23);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (24, 24);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (25, 25);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (26, 26);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (27, 27);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (28, 28);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (29, 29);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (30, 30);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (31, 31);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (32, 32);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (33, 33);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (34, 34);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (35, 35);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (36, 36);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (37, 37);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (38, 38);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (39, 39);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (40, 40);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (41, 41);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (42, 42);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (43, 43);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (44, 44);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (45, 45);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (46, 46);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (47, 47);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (48, 48);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (49, 49);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (50, 50);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (51, 51);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (52, 52);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (53, 53);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (54, 54);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (55, 55);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (56, 56);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (57, 57);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (58, 58);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (59, 59);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (60, 60);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (61, 61);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (62, 62);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (63, 63);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (64, 64);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (65, 65);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (66, 66);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (67, 67);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (68, 68);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (69, 69);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (70, 70);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (71, 71);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (72, 72);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (73, 73);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (74, 74);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (75, 75);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (76, 76);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (77, 77);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (78, 78);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (79, 79);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (80, 80);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (81, 81);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (82, 82);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (83, 83);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (84, 84);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (85, 85);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (86, 86);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (87, 87);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (88, 88);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (89, 89);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (90, 90);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (91, 91);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (92, 92);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (93, 93);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (94, 94);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (95, 95);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (96, 96);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (97, 97);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (98, 98);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (99, 99);
INSERT INTO tbl_book_authors (Fk_Book, Fk_Author) VALUES (100, 100);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-001', 'loaned', 1);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-002', 'available', 2);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-003', 'loaned', 3);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-004', 'loaned', 4);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-005', 'loaned', 5);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-006', 'loaned', 6);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-007', 'available', 7);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-008', 'available', 8);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-009', 'loaned', 9);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-010', 'loaned', 10);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-011', 'available', 11);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-012', 'loaned', 12);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-013', 'loaned', 13);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-014', 'loaned', 14);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-015', 'available', 15);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-016', 'available', 16);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-017', 'available', 17);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-018', 'available', 18);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-019', 'available', 19);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-020', 'available', 20);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-021', 'loaned', 21);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-022', 'loaned', 22);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-023', 'available', 23);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-024', 'available', 24);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-025', 'available', 25);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-026', 'available', 26);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-027', 'available', 27);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-028', 'loaned', 28);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-029', 'available', 29);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-030', 'loaned', 30);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-031', 'loaned', 31);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-032', 'loaned', 32);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-033', 'loaned', 33);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-034', 'loaned', 34);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-035', 'available', 35);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-036', 'available', 36);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-037', 'loaned', 37);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-038', 'available', 38);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-039', 'available', 39);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-040', 'available', 40);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-041', 'available', 41);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-042', 'loaned', 42);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-043', 'available', 43);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-044', 'available', 44);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-045', 'loaned', 45);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-046', 'available', 46);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-047', 'available', 47);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-048', 'available', 48);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-049', 'loaned', 49);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-050', 'loaned', 50);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-051', 'available', 51);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-052', 'available', 52);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-053', 'loaned', 53);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-054', 'available', 54);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-055', 'available', 55);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-056', 'loaned', 56);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-057', 'available', 57);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-058', 'available', 58);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-059', 'loaned', 59);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-060', 'loaned', 60);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-061', 'loaned', 61);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-062', 'available', 62);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-063', 'loaned', 63);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-064', 'loaned', 64);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-065', 'available', 65);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-066', 'available', 66);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-067', 'loaned', 67);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-068', 'loaned', 68);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-069', 'loaned', 69);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-070', 'available', 70);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-071', 'available', 71);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-072', 'available', 72);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-073', 'loaned', 73);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-074', 'loaned', 74);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-075', 'available', 75);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-076', 'loaned', 76);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-077', 'available', 77);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-078', 'available', 78);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-079', 'available', 79);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-080', 'loaned', 80);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-081', 'loaned', 81);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-082', 'loaned', 82);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-083', 'available', 83);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-084', 'loaned', 84);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-085', 'available', 85);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-086', 'available', 86);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-087', 'loaned', 87);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-088', 'available', 88);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-089', 'available', 89);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-090', 'available', 90);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-091', 'available', 91);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-092', 'loaned', 92);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-093', 'loaned', 93);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-094', 'loaned', 94);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-095', 'available', 95);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-096', 'available', 96);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-097', 'available', 97);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-098', 'loaned', 98);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-099', 'loaned', 99);
INSERT INTO tbl_book_copies (Barcode, Fk_Status, Fk_Book) VALUES ('BC-100', 'available', 100);