#PERSONAS
CREATE TABLE Rol(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL UNIQUE,
    Creado_En DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE Estado_Usuario(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL UNIQUE,
    Creado_En DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE Estado_Dispositivo(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL UNIQUE,
    Creado_En DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE Tipo_Documento(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL UNIQUE,
    Abreviatura VARCHAR(10) NOT NULL UNIQUE,
    Creado_En DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE Pais(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(70) NOT NULL,
    Creado_En DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE Departamento(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(70) NOT NULL,
    Creado_En DATETIME DEFAULT CURRENT_TIMESTAMP,
    Pais_ID INT NOT NULL,
    INDEX (Pais_ID),
    CONSTRAINT Fk_Pais_ID FOREIGN KEY (Pais_ID) REFERENCES Pais(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT UQ_Nombre_PaisID UNIQUE (Nombre, Pais_ID)
);
CREATE TABLE Ciudad(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(70) NOT NULL,
    Creado_En DATETIME DEFAULT CURRENT_TIMESTAMP,
    Departamento_ID INT NOT NULL,
    INDEX (Departamento_ID),
    CONSTRAINT Fk_Departamento_ID FOREIGN KEY (Departamento_ID) REFERENCES Departamento(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT UQ_NombreDepartamento_ID UNIQUE (Nombre, Departamento_ID)
);
CREATE TABLE Localidad(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(70) NOT NULL,
    Creado_En DATETIME DEFAULT CURRENT_TIMESTAMP,
    Ciudad_ID INT NOT NULL,
    INDEX (Ciudad_ID),
    CONSTRAINT Fk_Ciudad_ID FOREIGN KEY (Ciudad_ID) REFERENCES Ciudad(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT UQ_Nombre_CiudadID UNIQUE (Nombre, Ciudad_ID)
);
CREATE TABLE Barrio(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(70) NOT NULL,
    Creado_En DATETIME DEFAULT CURRENT_TIMESTAMP,
    Localidad_ID INT NOT NULL,
    INDEX (Localidad_ID),
    CONSTRAINT Fk_Localidad_ID FOREIGN KEY (Localidad_ID) REFERENCES Localidad(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT UQ_Nombre_LocalidadID UNIQUE (Nombre, Localidad_ID)
);
CREATE TABLE Usuario(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL UNIQUE,
    Correo VARCHAR(100) NOT NULL UNIQUE,
    Contraseña VARCHAR(255) NOT NULL,
    Intentos_Fallidos INT NOT NULL DEFAULT 0,
    Bloqueado_Hasta DATETIME NULL, 
    Creado_En DATETIME DEFAULT CURRENT_TIMESTAMP,
    Actualizado_En DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    Autenticador TINYINT NOT NULL DEFAULT 0,
	Autenticador_Secreto VARCHAR(255) NULL,
    Estado_Usuario_ID INT NOT NULL,
    Rol_ID INT NOT NULL,
	INDEX (Rol_ID),
	INDEX (Estado_Usuario_ID),
    CONSTRAINT FK_Rol_ID FOREIGN KEY (Rol_ID) REFERENCES Rol(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT FK_Estado_Usuario_ID FOREIGN KEY (Estado_Usuario_ID) REFERENCES Estado_Usuario(ID) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE TABLE Usuario_Auditoria(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Accion VARCHAR(100) NOT NULL,
    Modificado_Por INT NOT NULL,
    Fecha_Modificacion DATETIME DEFAULT CURRENT_TIMESTAMP,
    Usuario_ID INT NOT NULL,
    INDEX(Usuario_ID),
    INDEX(Modificado_Por),
    CONSTRAINT Fk_Usuario_Auditoria_ID FOREIGN KEY (Usuario_ID) REFERENCES Usuario(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT Fk_Usuario_Modificado_Por FOREIGN KEY (Modificado_Por) REFERENCES Usuario(ID) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE TABLE Persona(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    Tipo_Documento_ID INT NOT NULL,
    Documento VARCHAR(20) NOT NULL,
    Primer_Nombre VARCHAR(50) NOT NULL,
    Segundo_Nombre VARCHAR(50) DEFAULT NULL,
    Primer_Apellido VARCHAR(50) NOT NULL,
    Segundo_Apellido VARCHAR(50) DEFAULT NULL,
    Direccion VARCHAR(255) NOT NULL,
    Telefono VARCHAR(15) NOT NULL,
    Terminos_Condiciones TINYINT NOT NULL,
    Fecha_Nacimiento DATE NOT NULL,
    Creado_En DATETIME DEFAULT CURRENT_TIMESTAMP,
    Actualizado_En DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    Usuario_ID INT NOT NULL UNIQUE,
    Barrio_ID INT NOT NULL,
    INDEX (Tipo_Documento_ID),
    INDEX (Usuario_ID),
    INDEX (Barrio_ID),
    CONSTRAINT Fk_Tipo_Documento_ID FOREIGN KEY (Tipo_Documento_ID) REFERENCES Tipo_Documento(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT Fk_Usuario_ID FOREIGN KEY (Usuario_ID) REFERENCES Usuario(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT Fk_Barrio_ID FOREIGN KEY (Barrio_ID) REFERENCES Barrio(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT UQ_TipoDocumento_Documento UNIQUE (Tipo_Documento_ID, Documento)
);
CREATE TABLE Persona_Auditoria(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Accion VARCHAR(100) NOT NULL,
    Modificado_Por INT NOT NULL,
    Fecha_Modificacion DATETIME DEFAULT CURRENT_TIMESTAMP,
    Persona_ID INT NOT NULL,
    INDEX(Persona_ID),
    INDEX(Modificado_Por),
    CONSTRAINT Fk_Persona_Auditoria_ID FOREIGN KEY (Persona_ID) REFERENCES Persona(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT Fk_Persona_Modificado_Por FOREIGN KEY (Modificado_Por) REFERENCES Usuario(ID) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE TABLE Dispositivos(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IP VARCHAR(15) NOT NULL,
    Token VARCHAR(255) NOT NULL UNIQUE,
    Navegador VARCHAR(120) NOT NULL,
    Sistema VARCHAR(50) NOT NULL,
    Dispositivo VARCHAR(120) NOT NULL,
    Fecha_Conexion DATETIME DEFAULT CURRENT_TIMESTAMP,
    Ultimo_Uso DATETIME NOT NULL,
    Estado_Dispositivo_ID INT NOT NULL,
    Usuario_ID INT NOT NULL,
    INDEX (Estado_Dispositivo_ID),
    INDEX (Usuario_ID),
    CONSTRAINT Fk_Estado_Dispositivo_ID FOREIGN KEY (Estado_Dispositivo_ID) REFERENCES Estado_Dispositivo(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT Fk_Usuario_Dispositivo_ID FOREIGN KEY (Usuario_ID) REFERENCES Usuario(ID) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE TABLE Dispositivos_Auditoria(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Accion VARCHAR(100) NOT NULL,
    Modificado_Por INT NOT NULL,
    Fecha_Modificacion DATETIME DEFAULT CURRENT_TIMESTAMP,
    Dispositivos_ID INT NOT NULL,
    INDEX(Dispositivos_ID),
    INDEX(Modificado_Por),
    CONSTRAINT Fk_Dispositivos_Auditoria_ID FOREIGN KEY (Dispositivos_ID) REFERENCES Dispositivos(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT Fk_Dispositivos_Modificado_Por FOREIGN KEY (Modificado_Por) REFERENCES Usuario(ID) ON DELETE RESTRICT ON UPDATE CASCADE
);
#Formularios
CREATE TABLE Tipo_Formulario(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL,
    Creado_En DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE Calificanos(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL,
    Pregunta1 VARCHAR(100) NOT NULL,
    Pregunta2 VARCHAR(100) NOT NULL,
    Pregunta3 VARCHAR(100) NOT NULL,
    Pregunta4 VARCHAR(100) NOT NULL,
    Creado_En DATETIME DEFAULT CURRENT_TIMESTAMP,
    Tipo_Formulario_ID INT NOT NULL,
    INDEX(Tipo_Formulario_ID),
    CONSTRAINT Fk_Calificanos_Tipo_Formulario_ID FOREIGN KEY (Tipo_Formulario_ID) REFERENCES Tipo_Formulario(ID) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE TABLE Ayuda(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL,
    Soporte VARCHAR(255) NOT NULL,
    Creado_En DATETIME DEFAULT CURRENT_TIMESTAMP,
    Tipo_Formulario_ID INT NOT NULL,
    INDEX(Tipo_Formulario_ID),
    CONSTRAINT Fk_Ayuda_Tipo_Formulario_ID FOREIGN KEY (Tipo_Formulario_ID) REFERENCES Tipo_Formulario(ID) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE TABLE Contactanos(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL,
    Telefono VARCHAR(12) NOT NULL,
    Correo VARCHAR(100) NOT NULL,
    Mensaje VARCHAR(255) NOT NULL,
    Creado_En DATETIME DEFAULT CURRENT_TIMESTAMP,
    Tipo_Formulario_ID INT NOT NULL,
    INDEX(Tipo_Formulario_ID),
    CONSTRAINT Fk_Contactanos_Tipo_Formulario_ID FOREIGN KEY (Tipo_Formulario_ID) REFERENCES Tipo_Formulario(ID) ON DELETE RESTRICT ON UPDATE CASCADE
);
#Casos
CREATE TABLE Estado_Caso(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL UNIQUE,
    Creado_En DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE Prioridad(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Prioridad VARCHAR(30) NOT NULL
);
CREATE TABLE Incidente(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Incidente VARCHAR(40) NOT NULL,
    Prioridad_ID INT NOT NULL,
    INDEX(Prioridad_ID),
    CONSTRAINT Fk_Prioridad_ID FOREIGN KEY (Prioridad_ID) REFERENCES Prioridad(ID) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE TABLE Caso(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Creacion DATETIME DEFAULT CURRENT_TIMESTAMP,
    Descripcion VARCHAR(255) NOT NULL,
    Afectados INT NOT NULL,
    Direccion VARCHAR(60) NOT NULL,
    Caso_Asociado VARCHAR(10) NOT NULL,
    Usuario_ID INT NOT NULL,
    Incidente_ID INT NOT NULL,
    Estado_Caso_ID  INT NOT NULL,
    Prioridad_ID  INT NOT NULL,
    Barrio_ID  INT NOT NULL,
    INDEX(Usuario_ID),
    INDEX(Incidente_ID),
    INDEX(Estado_Caso_ID),
    INDEX(Prioridad_ID),
    INDEX(Barrio_ID),
    CONSTRAINT Fk_Usuario_Caso_ID FOREIGN KEY (Usuario_ID) REFERENCES Usuario(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT Fk_Incidente_Caso_ID FOREIGN KEY (Incidente_ID) REFERENCES Incidente(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT Fk_Estado_Caso_ID FOREIGN KEY (Estado_Caso_ID) REFERENCES Estado_Caso(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT Fk_Prioridad_Caso_ID FOREIGN KEY (Prioridad_ID) REFERENCES Prioridad(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT Fk_Barrio_Caso_ID FOREIGN KEY (Barrio_ID) REFERENCES Barrio(ID) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE TABLE Caso_Auditoria(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Accion VARCHAR(100) NOT NULL,
    Modificado_Por INT NOT NULL,
    Fecha_Modificacion DATETIME DEFAULT CURRENT_TIMESTAMP,
    Caso_ID INT NOT NULL,
    INDEX(Caso_ID),
    INDEX(Modificado_Por),
    CONSTRAINT Fk_Caso_Auditoria_ID FOREIGN KEY (Caso_ID) REFERENCES Caso(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT Fk_Caso_Modificado_Por FOREIGN KEY (Modificado_Por) REFERENCES Usuario(ID) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE TABLE Radicado_Caso(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Radicado VARCHAR(40) NOT NULL UNIQUE,
    Caso_ID INT NOT NULL,
    INDEX(Caso_ID),
    CONSTRAINT Fk_Caso_ID FOREIGN KEY (Caso_ID) REFERENCES Caso(ID) ON DELETE RESTRICT ON UPDATE CASCADE
);
#Entidad
CREATE TABLE Estado_Entidad(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL UNIQUE,
    Creado_En DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE Entidad(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL,
    Direccion VARCHAR(70) NOT NULL,
    Telefono VARCHAR(15) NOT NULL,
    Website VARCHAR(50) NOT NULL,
    Descripcion VARCHAR(255) NOT NULL,
    Incidente_ID INT NOT NULL,
    Estado_Entidad_ID INT NOT NULL,
    INDEX(Incidente_ID),
    INDEX(Estado_Entidad_ID),
    CONSTRAINT Fk_Incidente_ID FOREIGN KEY (Incidente_ID) REFERENCES Incidente(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT Fk_Estado_Entidad_ID FOREIGN KEY (Estado_Entidad_ID) REFERENCES Estado_Entidad(ID) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE TABLE Entidad_Auditoria(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Accion VARCHAR(100) NOT NULL,
    Modificado_Por INT NOT NULL,
    Fecha_Modificacion DATETIME DEFAULT CURRENT_TIMESTAMP,
    Entidad_ID INT NOT NULL,
    INDEX(Entidad_ID),
    INDEX(Modificado_Por),
    CONSTRAINT Fk_Entidad_Auditoria_ID FOREIGN KEY (Entidad_ID) REFERENCES Entidad(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT Fk_Entidad_Modificado_Por FOREIGN KEY (Modificado_Por) REFERENCES Usuario(ID) ON DELETE RESTRICT ON UPDATE CASCADE
);